name: df-file-interchange
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pydantic >= 2.7
  - pydantic-settings
  - numpy
  - pandas
  - pyarrow
  - ipykernel
  - loguru
  # - black
  # - black-jupyter
  - pytest
  # - isort
  - mypy
  - pyyaml
  - ruff
  - mkdocs