name: df-file-interchange
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pydantic >= 2.7
  - pydantic-settings
  - numpy
  - pandas
  - pyarrow
  - loguru
  - pyyaml
# dev/test
  - ruff
  - pytest
  - mypy
  - ipykernel
# docs
  - mkdocs
  - mkdocs-material
  - mknotebooks
  - mkdocstrings
  - mkdocstrings-python
  - mkdocstrings-python-xref
  - mkdocs-gen-files
  - mkdocs-literate-nav
  - pygments
# pip goes last
  - pip