site_name: DataFrames File Interchange
nav:
  - Home: index.md
  - Tutorials:
    - Getting Started: getting_started.md
    - Notebook Simple Write and Read: notebooks/tutorial_simple_write_read.ipynb
  - Code Reference:
    - file (read & write): code_reference__file.md
    - ci (custom information): code_reference__ci.md
  - Technical Background: background.md
  - YAML Fields: yaml_fields.md
  # - About: about.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            parameter_headings: true
            show_signature: true
            show_signature_annotations: true
            show_object_full_path: false
            show_root_heading: true
            # show_symbol_type_heading: true
            docstring_style: numpy
  - mknotebooks
  # - gen-files:
  #     scripts:
  #     - scripts/gen_ref_pages.py
  # - literate-nav:
  #     nav_file: summary.md
theme: material
