# name: do_tests

# on: ["pull_request"]

# jobs: 

#  test_development:
#   # Testing in development environment: functionality and code-format
#   # From https://github.com/marketplace/actions/setup-miniconda#caching-packages  
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash -l {0}

#     steps:
#     - name: Check out repository code
#       uses: actions/checkout@v4

#     - name: Cache conda
#       uses: actions/cache@v3
#       env:
#         # Increase this value to reset cache if environment.yaml has not changed
#         CACHE_NUMBER: 0
#       with:
#         path: ~/conda_pkgs_dir
#         # Note (EsmeMaxwell: make sure to change environment.yaml below to match what you're using!)
#         key:
#           ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
#           hashFiles('environment.yaml') }}

#     - name: Setup conda and environment
#       uses: conda-incubator/setup-miniconda@v3
#       with:
#           auto-update-conda: true
#           miniforge-variant: Mambaforge
#           miniforge-version: latest
#           use-mamba: true
#           channels: conda-forge
#           mamba-version: "*"
#           channel-priority: strict
#           activate-environment: df-file-interchange
#           environment-file: environment.yaml
#           use-only-tar-bz2: true   # required for caching

#     - name: List environment
#       run: |
#         mamba info
#         mamba list

#     - name: Run tests
#       run: |
#          isort --check-only .
#          coverage run --source=country_converter -m pytest --black -vv



#  test_production:
#    # Testing if the package runs on different systems/python versions
#     needs: test_development
#     runs-on: ${{ matrix.os }}
#     defaults:
#       run:
#         # removed -l as this breaks in mac-os
#         shell: bash {0}
#     strategy:
#       fail-fast: false
#       matrix:
#         os: ["ubuntu-latest", "macos-latest", "windows-latest"]
#         python-version: [3.7, 3.8, 3.9, "3.10"]

#     steps:
#        - name: Check out repository code
#          uses: actions/checkout@v3

#        - name: Setup Python
#          uses: actions/setup-python@v4
#          with:
#             python-version: ${{matrix.python-version}}
#             cache: 'pip'
#             cache-dependency-path: pyproject.toml

#        - name: Install and run tests
#          run: |
#             python -m pip install --upgrade pip
#             pip install -e .[dev]
#             pytest -vv